<a href="https://colab.research.google.com/github/mahadi0007/Ml-classification-experiments/blob/main/Seed_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from numpy import argmax
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
# Load the dataset from GitHub
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/00236/seeds_dataset.txt"
columns = [
    "area",             # Area of the kernel
    "perimeter",        # Perimeter of the kernel
    "compactness",      # Compactness (4*pi*area / perimeter^2)
    "kernel_length",    # Length of the kernel
    "kernel_width",     # Width of the kernel
    "asymmetry_coef",   # Asymmetry coefficient
    "groove_length",    # Length of the kernel groove
    "class"             # Class (1 = Kama, 2 = Rosa, 3 = Canadian)
]

# Load the dataset
seeds = pd.read_csv(url, delim_whitespace=True, header=None, names=columns)
df = seeds
# Display the first few rows
print(df)

<ipython-input-23-d58bfe9a68df>:15: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  seeds = pd.read_csv(url, delim_whitespace=True, header=None, names=columns)


      area  perimeter  compactness  kernel_length  kernel_width  \
0    15.26      14.84       0.8710          5.763         3.312   
1    14.88      14.57       0.8811          5.554         3.333   
2    14.29      14.09       0.9050          5.291         3.337   
3    13.84      13.94       0.8955          5.324         3.379   
4    16.14      14.99       0.9034          5.658         3.562   
..     ...        ...          ...            ...           ...   
205  12.19      13.20       0.8783          5.137         2.981   
206  11.23      12.88       0.8511          5.140         2.795   
207  13.20      13.66       0.8883          5.236         3.232   
208  11.84      13.21       0.8521          5.175         2.836   
209  12.30      13.34       0.8684          5.243         2.974   

     asymmetry_coef  groove_length  class  
0             2.221          5.220      1  
1             1.018          4.956      1  
2             2.699          4.825      1  
3             2.259

In [ ]:
# Count missing values in each column
missing_values = df.isna().sum()
print("\nMissing values:\n", missing_values)

# Check unique classes in the target column
print("\nUnique classes in the 'class' column:", df['class'].unique())


Missing values:
 area              0
perimeter         0
compactness       0
kernel_length     0
kernel_width      0
asymmetry_coef    0
groove_length     0
class             0
dtype: int64

Unique classes in the 'class' column: [1 2 3]


In [ ]:
# split into input and output columns
X, y = df.values[:, :-1], df.values[:, -1]

y= y - 1

X,y

(array([[15.26  , 14.84  ,  0.871 , ...,  3.312 ,  2.221 ,  5.22  ],
        [14.88  , 14.57  ,  0.8811, ...,  3.333 ,  1.018 ,  4.956 ],
        [14.29  , 14.09  ,  0.905 , ...,  3.337 ,  2.699 ,  4.825 ],
        ...,
        [13.2   , 13.66  ,  0.8883, ...,  3.232 ,  8.315 ,  5.056 ],
        [11.84  , 13.21  ,  0.8521, ...,  2.836 ,  3.598 ,  5.044 ],
        [12.3   , 13.34  ,  0.8684, ...,  2.974 ,  5.637 ,  5.063 ]]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1.,

In [ ]:
# ensure all data are floating point values and scale them
X = X.astype('float32')
scaler_X= MinMaxScaler()
scaler_X.fit(X)
X = scaler_X.transform(X)
print(X)

[[0.44098198 0.50206614 0.57078075 ... 0.48610127 0.18930164 0.34515   ]
 [0.40509915 0.44628096 0.6624322  ... 0.50106895 0.03288303 0.2151649 ]
 [0.34938622 0.3471074  0.8793106  ... 0.50391996 0.251453   0.15066457]
 ...
 [0.24645889 0.2582643  0.72776794 ... 0.4290806  0.98166656 0.2644019 ]
 [0.11803591 0.16528916 0.39927435 ... 0.14682806 0.36834443 0.25849342]
 [0.16147304 0.19214869 0.54718685 ... 0.24518883 0.6334629  0.2678485 ]]


In [ ]:
# split into trainand testdatasets
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.33)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
# determine the number of input features
n_features = X_train.shape[1]
# create dictionary of target classes
label_dict = {
  0: 'Kama',
  1: 'Rosa',
  2: 'Canadian'
}

(140, 7) (70, 7) (140,) (70,)


In [ ]:
# definemodel
model= Sequential()
model.add(Dense(32, activation='relu', kernel_initializer='he_normal',
input_shape=(n_features,)))
model.add(Dense(8, activation='relu', kernel_initializer='he_normal'))
model.add(Dense(3, activation='softmax'))
# compilethemodel
model.compile(optimizer='adam',
loss='sparse_categorical_crossentropy', metrics=['accuracy'])
# fitthemodel
model.fit(X_train, y_train, epochs=500, batch_size=32, verbose=0)
# evaluate the model
loss, acc = model.evaluate(X_test, y_test, verbose=0)
print('Test Accuracy: %.3f' % acc)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Test Accuracy: 0.957


In [ ]:
sample_input = [[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]]

# Scale the sample input using the same scaler used for training
sample_input_scaled = scaler_X.transform(sample_input)

# Make a prediction
prediction = model.predict(sample_input_scaled)

# Get the predicted class
predicted_class_index = np.argmax(prediction)
predicted_class_label = label_dict[predicted_class_index]

# Print the predicted class
print("Predicted Class:", predicted_class_label)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step
Predicted Class: Canadian
